# Generated by Django 4.2 on 2024-01-24 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliasTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название команды', max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название команды',
                'verbose_name_plural': 'Команды',
                'ordering': ('team', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorer', models.CharField(help_text='Имя бомбардира', max_length=50, verbose_name='Имя')),
                ('minute', models.PositiveSmallIntegerField(default=0, help_text='На какой минуте', verbose_name='Минута')),
                ('choice_team', models.SmallIntegerField(choices=[(1, 'First'), (2, 'Second')], help_text='Из какой команды', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Гол',
                'verbose_name_plural': 'Голы',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата матча', verbose_name='Дата')),
                ('goals1', models.PositiveSmallIntegerField(default=0, help_text='Голы первой команды', verbose_name='Голы 1')),
                ('goals2', models.PositiveSmallIntegerField(default=0, help_text='Голы второй команды', verbose_name='Голы 2')),
                ('is_neutral', models.BooleanField(help_text='Нейтральное ли поле', verbose_name='Нейтральность')),
                ('country', models.CharField(blank=True, help_text='Страна проведения', max_length=50, null=True, verbose_name='Старана')),
                ('city', models.CharField(blank=True, help_text='Город проведения', max_length=50, null=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название турнира', max_length=100, unique=True, verbose_name='Название')),
                ('coefficient', models.FloatField(default=1, help_text='Коэффициент - вес турнира', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Коэф.')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('goal', models.OneToOneField(help_text='Гол', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='note', serialize=False, to='kaggle.goal', verbose_name='Голы')),
                ('type', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Penalty'), (2, 'Own goal')], default=0, help_text='Примечание', verbose_name='Прим.')),
            ],
        ),
        migrations.CreateModel(
            name='Shootout',
            fields=[
                ('match', models.OneToOneField(help_text='Матч', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shootout', serialize=False, to='kaggle.match', verbose_name='Матч')),
                ('choice_winner', models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'First'), (2, 'Second')], default=0, help_text='Победитель', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Послематчевые пенальти',
                'verbose_name_plural': 'Пенальти',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.ForeignKey(blank=True, help_text='Название команды', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='kaggle.aliasteam', unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(help_text='Первая команда', on_delete=django.db.models.deletion.CASCADE, related_name='matches1', to='kaggle.team', verbose_name='Команда 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(help_text='Вторая команда', on_delete=django.db.models.deletion.CASCADE, related_name='matches2', to='kaggle.team', verbose_name='Команда 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(help_text='Турнир', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='kaggle.tournament', verbose_name='Турнир'),
        ),
        migrations.AddField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(help_text='Матч', on_delete=django.db.models.deletion.CASCADE, related_name='goalscore', to='kaggle.match', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='aliasteam',
            name='team',
            field=models.ForeignKey(help_text='Название команды', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='kaggle.team', verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('date', 'team1', 'team2'), name='unique_match'),
        ),
    ]
