# Generated by Django 4.2 on 2024-01-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='alias',
            field=models.ForeignKey(help_text='Название команды', on_delete=django.db.models.deletion.CASCADE, related_name='team3', to='kaggle.aliasteam', verbose_name='Название'),
        ),
    ]
