# Generated by Django 4.2 on 2024-01-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0002_alter_team_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='alias',
            field=models.ForeignKey(blank=True, help_text='Название команды', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='kaggle.aliasteam', verbose_name='Название'),
        ),
    ]
