# Generated by Django 4.2 on 2024-01-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0003_alter_team_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aliasteam',
            options={'ordering': ('team', 'name'), 'verbose_name': 'Название команды', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='aliasteam',
            name='team',
            field=models.ForeignKey(help_text='Название команды', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='kaggle.team', verbose_name='Название'),
        ),
    ]
