# Generated by Django 4.2 on 2023-08-15 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название команды', max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название турнира', max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата матча', verbose_name='Дата')),
                ('goals1', models.PositiveSmallIntegerField(default=0, help_text='Голы первой команды', verbose_name='Голы команды 1')),
                ('goals2', models.PositiveSmallIntegerField(default=0, help_text='Голы второй команды', verbose_name='Голы команды 2')),
                ('is_neutral', models.BooleanField(help_text='Нейтральное ли поле', verbose_name='Нейтральность')),
                ('country', models.CharField(blank=True, help_text='Страна проведения', max_length=50, null=True, verbose_name='Старана')),
                ('city', models.CharField(blank=True, help_text='Город проведения', max_length=50, null=True, verbose_name='Город')),
                ('team1', models.ForeignKey(help_text='Первая команда', on_delete=django.db.models.deletion.CASCADE, related_name='matches1', to='kaggle.team', verbose_name='Команда 1')),
                ('team2', models.ForeignKey(help_text='Вторая команда', on_delete=django.db.models.deletion.CASCADE, related_name='matches2', to='kaggle.team', verbose_name='Команда 2')),
                ('tournament', models.ForeignKey(help_text='Турнир', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='kaggle.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Shootout',
            fields=[
                ('match', models.OneToOneField(help_text='Матч', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kaggle.match', verbose_name='Матч')),
                ('winner', models.ForeignKey(help_text='Победитель', on_delete=django.db.models.deletion.CASCADE, to='kaggle.team', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Пенальти',
                'verbose_name_plural': 'Пенальти',
            },
        ),
    ]
