# Generated by Django 4.2 on 2023-08-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Penalty'), (2, 'Own goal')], default=0, help_text='Примечание', verbose_name='Прим.'),
        ),
    ]
