# Generated by Django 4.2 on 2023-08-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goals1',
            field=models.PositiveSmallIntegerField(default=0, help_text='Голы первой команды', verbose_name='Голы 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals2',
            field=models.PositiveSmallIntegerField(default=0, help_text='Голы второй команды', verbose_name='Голы 2'),
        ),
    ]
