# Generated by Django 4.2 on 2023-08-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0002_goal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(help_text='Матч', on_delete=django.db.models.deletion.CASCADE, related_name='goalscore', to='kaggle.match', verbose_name='Матч'),
        ),
    ]
