# Generated by Django 4.2 on 2023-08-16 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0003_alter_shootout_match_alter_shootout_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootout',
            name='match',
            field=models.OneToOneField(help_text='Матч', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kaggle.match', verbose_name='Матч'),
        ),
    ]
