# Generated by Django 4.2 on 2023-08-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0004_alter_shootout_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shootout',
            old_name='winner',
            new_name='numb_winner',
        ),
    ]
