# Generated by Django 4.2 on 2023-08-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0007_remove_shootout_id_alter_shootout_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shootout',
            options={'verbose_name': 'Послематчевые пенальти', 'verbose_name_plural': 'Пенальти'},
        ),
    ]
