# Generated by Django 4.2 on 2023-10-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0009_match_unique_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shootout',
            options={'verbose_name': 'Послематчевые пенальти', 'verbose_name_plural': 'Пенальти2'},
        ),
        migrations.AddField(
            model_name='shootout',
            name='caption',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
