# Generated by Django 4.2 on 2023-10-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0010_alter_shootout_options_shootout_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shootout',
            name='caption',
        ),
    ]
