# Generated by Django 4.2 on 2023-10-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0012_alter_shootout_options_remove_goal_status_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AlterField(
            model_name='note',
            name='goal',
            field=models.OneToOneField(help_text='Гол', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='goal', serialize=False, to='kaggle.goal', verbose_name='Голы'),
        ),
    ]
