# Generated by Django 4.2 on 2023-10-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaggle', '0013_remove_note_id_alter_note_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='goal',
            field=models.OneToOneField(help_text='Гол', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='note', serialize=False, to='kaggle.goal', verbose_name='Голы'),
        ),
    ]
